apiVersion: v1
kind: Secret
metadata:
  name: helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: helm
  url: https://github.com/TheAutomationRules/helm.git